{
  "espana": [
    "Real Madrid",
    "Barcelona",
    "Atlético Madrid",
    "Sevilla",
    "Valencia",
    "Villarreal",
    "Real Sociedad",
    "Betis",
    "Athletic Club",
    "Celta Vigo",
    "Granada",
    "Osasuna",
    "Espanyol",
    "Mallorca",
    "Getafe",
    "Alavés",
    "Elche",
    "Rayo Vallecano",
    "Cadiz",
    "Real Valladolid"
  ],
  "alemania": [
    "Bayern Munich",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    "VfL Wolfsburg",
    "Eintracht Frankfurt",
    "Union Berlin",
    "SC Freiburg",
    "Borussia M'Gladbach",
    "1. FC Köln",
    "VfB Stuttgart",
    "Mainz 05",
    "FC Augsburg",
    "Hertha BSC",
    "Werder Bremen",
    "Freiburg",
    "Hoffenheim",
    "FC Schalke 04"
  ],
  "francia": [
    "Paris Saint-Germain",
    "Olympique Lyonnais",
    "Olympique de Marseille",
    "AS Monaco",
    "LOSC Lille",
    "Stade Rennais",
    "OGC Nice",
    "Montpellier HSC",
    "RC Strasbourg",
    "FC Nantes",
    "Angers SCO",
    "FC Metz",
    "Bordeaux",
    "Reims",
    "Toulouse FC",
    "Lens",
    "Clermont Foot",
    "Lorient",
    "Ajaccio",
    "Troyes"
  ],
  "inglaterra": [
    "Manchester City",
    "Manchester United",
    "Liverpool",
    "Chelsea",
    "Arsenal",
    "Tottenham Hotspur",
    "Leicester City",
    "West Ham United",
    "Everton",
    "Aston Villa",
    "Newcastle United",
    "Crystal Palace",
    "Wolverhampton Wanderers",
    "Brighton & Hove Albion",
    "Brentford",
    "Fulham",
    "Southampton",
    "Leeds United",
    "Bournemouth",
    "Nottingham Forest"
  ],
  "italia": [
    "Inter Milan",
    "AC Milan",
    "Juventus",
    "Napoli",
    "AS Roma",
    "Lazio",
    "Atalanta",
    "Fiorentina",
    "Torino",
    "Sassuolo",
    "Sampdoria",
    "Udinese",
    "Bologna",
    "Genoa",
    "Empoli",
    "Salernitana",
    "Monza",
    "Lecce",
    "Verona",
    "Cremonese"
  ],
  "portugal": [
    "Benfica",
    "Porto",
    "Sporting CP",
    "Braga",
    "Vitória SC",
    "Famalicão",
    "Marítimo",
    "Santa Clara",
    "Gil Vicente",
    "Boavista",
    "Paços de Ferreira",
    "Moreirense",
    "Portimonense",
    "Estoril",
    "Tondela",
    "Vizela",
    "Belenenses SAD",
    "Casa Pia",
    "Chaves",
    "Arouca"
  ],
  "holanda": [
    "Ajax",
    "PSV Eindhoven",
    "Feyenoord",
    "AZ Alkmaar",
    "FC Utrecht",
    "Vitesse",
    "Heerenveen",
    "Groningen",
    "Sparta Rotterdam",
    "Twente",
    "Fortuna Sittard",
    "Cambuur",
    "Excelsior",
    "Go Ahead Eagles",
    "RKC Waalwijk",
    "PEC Zwolle",
    "NEC Nijmegen",
    "Volendam",
    "De Graafschap",
    "Emmen"
  ]
}
